<a href="https://colab.research.google.com/github/walperju/GoogleCollab/blob/main/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd #tratar dados tabulares , ou seja em linhas e colunas
import numpy as np #tratar dados na forma de vetores e matrizes , muito usado para AI
from sklearn.model_selection import train_test_split #usado para dividir em conjunto de treino e conjunto de testes
from sklearn.naive_bayes import GaussianNB #usada para criar o modelo , que no momento é o Naive-Bayes do tipo Gaussian NB
from sklearn.preprocessing import LabelEncoder #usado para codificar os dados, transformar os dados categoricos em numericos para que as bibliotcas sejam capazes de compreender e processar.
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report #contem as metricas usadas para calcular a regressao linear
from yellowbrick.classifier import ConfusionMatrix #usada para gerar a matriz de confusao em classificacoes

In [3]:
base = pd.read_csv("insurance.csv", keep_default_na=False)
base.head()

,Unnamed: 0,GoodStudent,Age,SocioEcon,RiskAversion,VehicleYear,ThisCarDam,RuggedAuto,Accident,MakeModel,...,HomeBase,AntiTheft,PropCost,OtherCarCost,OtherCar,MedCost,Cushioning,Airbag,ILiCost,DrivHist
0,1,False,Adult,Prole,Adventurous,Older,Moderate,EggShell,Mild,Economy,...,City,False,TenThou,Thousand,True,Thousand,Poor,False,Thousand,Many
1,2,False,Senior,Prole,Cautious,Current,None,Football,None,Economy,...,City,True,Thousand,Thousand,True,Thousand,Good,True,Thousand,Zero
2,3,False,Senior,UpperMiddle,Psychopath,Current,None,Football,None,FamilySedan,...,City,False,Thousand,Thousand,False,Thousand,Good,True,Thousand,One
3,4,False,Adolescent,Middle,Normal,Older,None,EggShell,None,Economy,...,Suburb,False,Thousand,Thousand,True,Thousand,Fair,False,Thousand,Zero
4,5,False,Adolescent,Prole,Normal,Older,Moderate,Football,Moderate,Economy,...,City,False,TenThou,Thousand,False,Thousand,Fair,False,Thousand,Many

In [4]:
base = base.drop(columns=['Unnamed: 0'])
base.head()

,GoodStudent,Age,SocioEcon,RiskAversion,VehicleYear,ThisCarDam,RuggedAuto,Accident,MakeModel,DrivQuality,...,HomeBase,AntiTheft,PropCost,OtherCarCost,OtherCar,MedCost,Cushioning,Airbag,ILiCost,DrivHist
0,False,Adult,Prole,Adventurous,Older,Moderate,EggShell,Mild,Economy,Poor,...,City,False,TenThou,Thousand,True,Thousand,Poor,False,Thousand,Many
1,False,Senior,Prole,Cautious,Current,None,Football,None,Economy,Normal,...,City,True,Thousand,Thousand,True,Thousand,Good,True,Thousand,Zero
2,False,Senior,UpperMiddle,Psychopath,Current,None,Football,None,FamilySedan,Excellent,...,City,False,Thousand,Thousand,False,Thousand,Good,True,Thousand,One
3,False,Adolescent,Middle,Normal,Older,None,EggShell,None,Economy,Normal,...,Suburb,False,Thousand,Thousand,True,Thousand,Fair,False,Thousand,Zero
4,False,Adolescent,Prole,Normal,Older,Moderate,Football,Moderate,Economy,Poor,...,City,False,TenThou,Thousand,False,Thousand,Fair,False,Thousand,Many

In [5]:
base.shape

(20000, 27)

In [6]:
print(base.isnull().sum())

GoodStudent     0
Age             0
SocioEcon       0
RiskAversion    0
VehicleYear     0
ThisCarDam      0
RuggedAuto      0
Accident        0
MakeModel       0
DrivQuality     0
Mileage         0
Antilock        0
DrivingSkill    0
SeniorTrain     0
ThisCarCost     0
Theft           0
CarValue        0
HomeBase        0
AntiTheft       0
PropCost        0
OtherCarCost    0
OtherCar        0
MedCost         0
Cushioning      0
Airbag          0
ILiCost         0
DrivHist        0
dtype: int64

In [8]:
Y=base.iloc[:,7].values #coluna acidente que será a nossa classe , portanto y
X=base.drop(base.columns[7], axis=1).values
X

array([[False, 'Adult', 'Prole', ..., False, 'Thousand', 'Many'],
       [False, 'Senior', 'Prole', ..., True, 'Thousand', 'Zero'],
       [False, 'Senior', 'UpperMiddle', ..., True, 'Thousand', 'One'],
       ...,
       [False, 'Senior', 'UpperMiddle', ..., True, 'Thousand', 'Zero'],
       [False, 'Adult', 'Middle', ..., True, 'Thousand', 'Zero'],
       [False, 'Adult', 'Middle', ..., True, 'Thousand', 'Zero']],
      dtype=object)

In [11]:
labelencoder = LabelEncoder() #transforma a variavel independente CATEGORICA em uma variavel independente DISCRETA
for i in range(X.shape[1]):
  if X[:,i].dtype == 'object':
    X[:,i] = labelencoder.fit_transform(X[:,i])
X

array([[0, 1, 1, ..., 0, 3, 0],
       [0, 2, 1, ..., 1, 3, 2],
       [0, 2, 2, ..., 1, 3, 1],
       ...,
       [0, 2, 2, ..., 1, 3, 2],
       [0, 1, 0, ..., 1, 3, 2],
       [0, 1, 0, ..., 1, 3, 2]], dtype=object)

In [12]:
X_treinamento, X_test, Y_treinamento, Y_test = train_test_split(X, Y,test_size=0.3, random_state=12)

In [13]:
modelo = GaussianNB()
modelo.fit(X_treinamento, Y_treinamento)

GaussianNB()

In [15]:
previsoes = modelo.predict(X_test) #sempre que usar scikitLearn use o método predict

In [16]:
previsoes

array(['Moderate', 'Mild', 'Moderate', ..., 'None', 'Mild', 'None'],
      dtype='<U8')

In [17]:
accuracy = accuracy_score(Y_test, previsoes) #simplesmente o percentual de acerto
precision = precision_score(Y_test, previsoes, average='weighted')
recall = recall_score(Y_test, previsoes, average='weighted')
f1 = f1_score(Y_test, previsoes, average='weighted')
print(f'Acurácia:{accuracy},Precisão:{precision},Recall:{recall},F1_Score:{f1}')

Acurácia:0.857,Precisão:0.919107010136158,Recall:0.857,F1_Score:0.8343753099843555